[package]
name = "polylang-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
multi-cpu = ["polylang-prover/multi-cpu"]
metal = ["polylang-prover/metal"]

[dependencies]
polylang = { git = "https://github.com/polybase/polylang", rev = "fdfcc7c13abf722973f9bbf46545e6ae8791cda0" }
polylang-prover = { git = "https://github.com/polybase/polylang", rev = "fdfcc7c13abf722973f9bbf46545e6ae8791cda0" }
abi = { git = "https://github.com/polybase/polylang", rev = "fdfcc7c13abf722973f9bbf46545e6ae8791cda0" }
zstd = "0.12.4"

[dev-dependencies]
bench = { path = "../bench" }

[[bench]]
harness = false
name = "bench"
