[package]
name = "merkle_membership"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.17.0", default-features = false }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
shared = { path = "../../../shared" }
