name: Bench

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest-16-cores

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run benchmarks
      working-directory: ./miden
      run: |
        cargo bench
  