name: Test

on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest-16-cores

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Run Miden benchmarks
      working-directory: ./miden
      run: |
        cargo bench

    - name: Run Risc-Zero benchmarks
      working-directory: ./risc-zero/host
      run: |
        cargo bench
