name: Test

on:
  push:

jobs:
  miden:
    runs-on: ubuntu-latest-64-cores

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v2
  
    - name: Run Miden benchmarks
      working-directory: ./miden
      env:
        BENCH_QUICK: "1"
      run: |
        cargo bench -F multi-cpu

  risc_zero:
    runs-on: ubuntu-latest-64-cores

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Cache cargo bin
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
    
      - name: Install risczero
        run: cargo install cargo-risczero && cargo risczero install
  
      - name: Run Risc-Zero benchmarks
        working-directory: ./risc-zero/host
        env:
          BENCH_QUICK: "1"
        run: |
          cargo bench multi-cpu

  noir:
    runs-on: ubuntu-latest-64-cores

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Cache Nix packages
        uses: actions/cache@v2
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('**/shell.nix') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install)
          source $HOME/.nix-profile/etc/profile.d/nix.sh

      - name: Run cargo bench in Nix shell
        working-directory: ./noir
        env:
          BENCH_QUICK: "1"
        run: |
          source $HOME/.nix-profile/etc/profile.d/nix.sh
          nix-shell --run "cargo bench -q"